### ISSUE TITLE
Broken repo

### ISSUE THREAD

**Issue by rshadow** [xbmcrepo/rus#1]
I install last repo from `https://github.com/xbmcrepo/ru/raw/master/xbmcrepo.ru-1.0.4.zip`. But ca`t install addon:

00:20:08.685 T:139931373655808   ERROR: CCurlFile::Open failed with code 404 for https://github.com/xbmcrepo/ru/raw/master/plugin.video.mults.spb.ru/plugin.video.mults.spb.ru-1.0.3.zip

**Comment by xbmcrepo** [comment]
Роман, это свалка архивных плагинов. Не пользуйтесь этим git

**Comment by rshadow** [comment]
Понятно. Спасибо.
